spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/library

logging:
  level:
    root: INFO

scheduled-time: 0 18 11 * * *
#scheduled-time: 120000

data-retention:
  retention-period: 1
  adm100: 3
  adm150: 1
  isy100: 6


